export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILURE = "LOAD_USER_FAILURE";

export const LOAD_LIST_REQUEST = "LOAD_LIST_REQUEST";
export const LOAD_LIST_SUCCESS = "LOAD_LIST_SUCCESS";
export const LOAD_LIST_FAILURE = "LOAD_LIST_FAILURE";

export const LOAD_SIGNUP_REQUEST = "LOAD_SIGNUP_REQUEST";
export const LOAD_SIGNUP_SUCCESS = "LOAD_SIGNUP_SUCCESS";
export const LOAD_SIGNUP_FAILURE = "LOAD_SIGNUP_FAILURE";

export const LOAD_LECTURER_REQUEST = "LOAD_LECTURER_REQUEST";
export const LOAD_LECTURER_SUCCESS = "LOAD_LECTURERO_SUCCESS";
export const LOAD_LECTURER_FAILURE = "LOAD_LECTURER_FAILURE";

export const LOAD_TOOLID_REQUEST = "LOAD_TOOLID_REQUEST";
export const LOAD_TOOLID_SUCCESS = "LOAD_TOOLID_SUCCESS";
export const LOAD_TOOLID_FAILURE = "LOAD_TOOLID_FAILURE";

export const CREATE_CONTACT_REQUEST = "CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAILURE = "CREATE_CONTACT_FAILURE";

export const CHANGE_CONTACT_REQUEST = "CHANGE_CONTACT_REQUEST";
export const CHANGE_CONTACT_SUCCESS = "CHANGE_CONTACT_SUCCESS";
export const CHANGE_CONTACT_FAILURE = "CHANGE_CONTACT_FAILURE";

export const USE_SIGNUP_REQUEST = "USE_SIGNUP_REQUEST";
export const USE_SIGNUP_SUCCESS = "USE_SIGNUP_SUCCESS";
export const USE_SIGNUP_FAILURE = "USE_SIGNUP_FAILURE";

export const CHANGE_WEBSITE_REQUEST = "CHANGE_WEBSITE_REQUEST";
export const CHANGE_WEBSITE_SUCCESS = "CHANGE_WEBSITE_SUCCESS";
export const CHANGE_WEBSITE_FAILURE = "CHANGE_WEBSITE_FAILURE";

export const CHANGE_LOCATION_REQUEST = "CHANGE_LOCATION_REQUEST";
export const CHANGE_LOCATION_SUCCESS = "CHANGE_LOCATION_SUCCESS";
export const CHANGE_LOCATION_FAILURE = "CHANGE_LOCATION_FAILURE";

export const CHANGE_DATE_REQUEST = "CHANGE_DATE_REQUEST";
export const CHANGE_DATE_SUCCESS = "CHANGE_DATE_SUCCESS";
export const CHANGE_DATE_FAILURE = "CHANGE_DATE_FAILURE";

export const ADD_PERMISSION_REQUEST = "ADD_PERMISSION_REQUEST";
export const ADD_PERMISSION_SUCCESS = "ADD_PERMISSION_SUCCESS";
export const ADD_PERMISSION_FAILURE = "ADD_PERMISSION_FAILURE";